# Generated by Django 4.0.5 on 2022-06-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bait_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='UsuariosCadastrados',
        ),
    ]
