# Generated by Django 4.0.5 on 2022-06-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bait_form', '0002_rename_usuarios_usuarioscadastrados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuariosCadastrados',
            new_name='Usuario',
        ),
    ]
